import {
  BufferGeometry,
  DoubleSide,
  PlaneGeometry,
  ShaderMaterial,
  Mesh,
  Vector3,
  Vector4,
  Texture,
} from 'three';

// ---------------------------------------------------------------------------
// Wave configuration
// ---------------------------------------------------------------------------

/**
 * Parameters for a single Gerstner wave layer.
 *
 * - `amplitude`: Peak displacement from rest level (meters).
 * - `wavelength`: Distance between successive crests (meters).
 * - `speed`: Propagation speed (meters/second).
 * - `direction`: 2D unit vector `(dx, dz)` on the XZ plane.
 * - `steepness`: Shape parameter `q ∈ [0, 1]`.  `0` degenerates to a
 *   linear sine wave; values near `1` produce sharp, trochoidal crests.
 */
export interface GerstnerWaveConfig {
  amplitude: number;
  wavelength: number;
  speed: number;
  direction: [number, number];
  steepness: number;
}

/**
 * Configuration for the ocean mesh.
 */
export interface WaterMeshConfig {
  size: number;
  segments: number;
  waves: GerstnerWaveConfig[];

  /**
   * HDR environment map generated by PMREMGenerator.
   * Used for physically based reflections.
   */
  envMap?: Texture | null;

  /**
   * Spherical harmonic irradiance map for diffuse environment lighting.
   * When omitted, the shader falls back to a simple ambient term.
   */
  irradianceMap?: Texture | null;

  /**
   * Precomputed BRDF lookup texture (2D) for integrating the GGX
   * distribution over the environment map.  Generated offline or via
   * a dedicated BRDF shader.  When omitted, a closed-form approximation
   * is used in the shader.
   */
  brdfLUT?: Texture | null;

  /**
   * Surface roughness for the GGX distribution.
   * `0` = mirror-smooth, `1` = completely diffuse.
   * Water is typically 0.1–0.4 depending on wind.
   */
  roughness?: number;

  /**
   * Metalness factor.  Water is a dielectric so this stays `0`.
   * Kept for material compatibility with the standard PBR workflow.
   */
  metalness?: number;

  /**
   * Index of refraction for the Fresnel calculation.
   * Water ≈ 1.33, but can be tweaked for artistic effect.
   */
  ior?: number;

  /**
   * Deep water colour (troughs).
   */
  deepColor?: [number, number, number];

  /**
   * Shallow / surface colour (crests).
   */
  shallowColor?: [number, number, number];

  // ── Foam parameters ───────────────────────────────────────────────────

  /**
   * Foam colour applied at wave crests.
   */
  foamColor?: [number, number, number];

  /**
   * Minimum wave gradient magnitude (steepness) required for foam.
   * Lower values produce more foam across gentler waves.
   * Typical range: 0.1 – 0.8.
   */
  foamSteepnessThreshold?: number;

  /**
   * How sharply foam transitions from 0 to 1 based on steepness.
   * Higher = crisper foam edges.  Typical range: 2 – 20.
   */
  foamSteepnessSharpness?: number;

  /**
   * Distance from the mesh edge where shoreline foam appears (meters).
   * Set to 0 to disable shoreline foam.
   */
  shorelineFoamWidth?: number;

  /**
   * Opacity of shoreline foam (0 = none, 1 = full).
   */
  shorelineFoamOpacity?: number;

  /**
   * Circular shoreline distance fields.
   * Each entry: [x, z, radius, foamWidth].
   * Useful for islands/sandbars before a full depth buffer is available.
   */
  shorelineFoamSources?: number[][];

  /**
   * Positions of objects that break the water surface.
   * Foam accumulates around each position.
   * Each entry: [x, z, radius, foamWidth].
   *   - x, z: world-space position on the water plane
   *   - radius: object's effective radius at the water surface
   *   - foamWidth: how far foam spreads outward from the object
   */
  objectFoamSources?: number[][];

  /**
   * Seed for the procedural noise that modulates foam distribution.
   * Different values produce different foam patterns.
   */
  foamNoiseSeed?: number;

  /**
   * Frequency of the noise that breaks up foam organically.
   * Higher = more scattered, broken-up foam.
   */
  foamNoiseFrequency?: number;

  /**
   * Maximum foam opacity.  Even at full steepness, foam will not
   * exceed this value.  Typical range: 0.3 – 0.9.
   */
  foamMaxOpacity?: number;

  /**
   * Subsurface scattering approximation colour.
   * Simulates light that penetrates the surface and exits nearby.
   */
  sssColor?: [number, number, number];

  /**
   * Scale of the SSS effect.  Larger values let light penetrate deeper.
   */
  sssScale?: number;
}

const defaultConfig: WaterMeshConfig = {
  size: 1000,
  segments: 256,
  roughness: 0.15,
  metalness: 0.0,
  ior: 1.33,
  deepColor: [0.0, 0.05, 0.15],
  shallowColor: [0.0, 0.5, 0.6],
  foamColor: [0.95, 0.95, 0.95],
  foamSteepnessThreshold: 0.3,
  foamSteepnessSharpness: 8.0,
  shorelineFoamWidth: 8.0,
  shorelineFoamOpacity: 0.6,
  foamNoiseSeed: 42.0,
  foamNoiseFrequency: 3.0,
  foamMaxOpacity: 0.7,
  sssColor: [0.0, 0.35, 0.45],
  sssScale: 8.0,
  waves: [
    {
      amplitude: 2.0,
      wavelength: 40.0,
      speed: 12.0,
      direction: [1, 0.3],
      steepness: 0.4,
    },
    {
      amplitude: 1.0,
      wavelength: 12.0,
      speed: 6.0,
      direction: [0.5, 1],
      steepness: 0.5,
    },
    {
      amplitude: 0.5,
      wavelength: 5.0,
      speed: 3.0,
      direction: [-1, 0.7],
      steepness: 0.6,
    },
  ],
};

// ---------------------------------------------------------------------------
// GLSL constants
// ---------------------------------------------------------------------------

const MAX_WAVES = 8;
const MAX_FOAM_SOURCES = 8;
const MAX_SHORELINE_SOURCES = 8;

// ---------------------------------------------------------------------------
// Vertex shader
// ---------------------------------------------------------------------------
//
// Gerstner wave displacement — entirely in the vertex shader.
//
// For each wave layer i with parameters (A, q, λ, v, d):
//
//   k  = 2π / λ                          (wavenumber)
//   ω  = k * v                           (angular frequency)
//   φ  = k · (d · p₀) - ω * t            (phase, p₀ = original xz)
//
//   Displacement:
//     x' = x₀ - A * q * sin(φ) * dₓ
//     y' =  A * cos(φ)
//     z' = z₀ - A * q * sin(φ) * d_z
//
//   Analytical tangent vectors (partial derivatives w.r.t. original position):
//     ∂P/∂x₀ = (1 - A*q*k*dₓ²*cosφ,  -A*k*dₓ*sinφ,  -A*q*k*dₓ*d_z*cosφ)
//     ∂P/∂z₀ = (-A*q*k*dₓ*d_z*cosφ,  -A*k*d_z*sinφ,  1 - A*q*k*d_z²*cosφ)
//
//   Normal = normalize( cross( ∂P/∂x₀ , ∂P/∂z₀ ) )
//
//   Wave gradient magnitude (for foam):
//     |∇y| = sqrt( (∂y/∂x₀)² + (∂y/∂z₀)² )
//         = sqrt( (-A*k*dₓ*sinφ)² + (-A*k*d_z*sinφ)² )
//         = A * k * |sin(φ)|  * sqrt(dₓ² + d_z²)
//         = A * k * |sin(φ)|    (since d is a unit vector)
//
// Multiple layers are accumulated: displacement sums, and tangent
// components sum analytically (chain rule through the shared original
// position p₀).  No numerical finite-difference approximations.

const vertexShader = /* glsl */ `
  uniform float uTime;
  uniform int   uWaveCount;

  // Per-wave parameter arrays
  uniform float uAmplitude[${MAX_WAVES}];
  uniform float uWavelength[${MAX_WAVES}];
  uniform float uSpeed[${MAX_WAVES}];
  uniform vec2  uDirection[${MAX_WAVES}];
  uniform float uSteepness[${MAX_WAVES}];
  uniform float uMaxWaveHeight;

  varying vec3 vWorldPosition;
  varying vec3 vNormal;
  varying float vElevation;

  // Wave gradient magnitude for foam computation.
  // |∇y| = length(sum over all wave height derivatives)
  varying float vWaveGradient;

  void main() {
    vec3 p = position;                  // original vertex (y ≈ 0)
    vec2 p0 = p.xz;                     // original xz on the surface

    // Accumulators for analytical tangent vectors
    vec3 tx = vec3(1.0, 0.0, 0.0);     // ∂P/∂x₀  (starts at identity)
    vec3 tz = vec3(0.0, 0.0, 1.0);     // ∂P/∂z₀

    vec3 disp = vec3(0.0);
    vec2 grad = vec2(0.0);              // ∇y accumulator

    for (int i = 0; i < ${MAX_WAVES}; i++) {
      if (i >= uWaveCount) break;

      float A  = uAmplitude[i];
      float q  = uSteepness[i];
      float wl = uWavelength[i];
      float s  = uSpeed[i];
      vec2  d  = normalize(uDirection[i]);

      float k = 2.0 * 3.141592653589793 / wl;   // wavenumber
      float omega = k * s;                         // angular frequency
      float phi = k * dot(p0, d) - omega * uTime; // phase

      float sp = sin(phi);
      float cp = cos(phi);

      // -- Gerstner displacement ------------------------------------------
      disp.x += -A * q * sp * d.x;
      disp.y +=  A * cp;
      disp.z += -A * q * sp * d.y;

      // -- Analytical tangent contributions -------------------------------
      float aqk = A * q * k;

      tx.x += -aqk * d.x * d.x * cp;
      tx.y += -A * k * d.x * sp;
      tx.z += -aqk * d.x * d.y * cp;

      tz.x += -aqk * d.x * d.y * cp;
      tz.y += -A * k * d.y * sp;
      tz.z += -aqk * d.y * d.y * cp;

      // -- Gradient magnitude for foam ------------------------------------
      // ∂y/∂x₀ = -A * k * dₓ * sin(φ)
      // ∂y/∂z₀ = -A * k * d_z * sin(φ)
      grad += -A * k * sp * d;
    }

    vec3 pos = p + disp;

    // Analytical normal from cross product of tangent vectors
    vec3 normal = normalize(cross(tz, tx));

    vWorldPosition = (modelMatrix * vec4(pos, 1.0)).xyz;
    vNormal = normalize(normalMatrix * normal);
    vElevation = disp.y;
    vWaveGradient = length(grad);

    gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
  }
`;

// ---------------------------------------------------------------------------
// Fragment shader — Full Physically Based Water Rendering
// ---------------------------------------------------------------------------
//
// This shader implements a complete PBR water model built on the
// Cook-Torrance microfacet BRDF with the following components:
//
//   1. Schlick Fresnel approximation          — angle-dependent reflectance
//   2. GGX / Trowbridge-Reitz NDF             — microfacet normal distribution
//   3. Smith geometric shadowing (Schlick-GGX) — visibility / masking term
//   4. Cook-Torrance specular BRDF             — combines D, G, F
//   5. Energy-conserving diffuse                — (1-F) partition, metalness
//   6. HDR environment map reflections          — prefiltered via PMREM
//   7. BRDF integration for rough env maps     — precomputed or analytical
//   8. Fresnel-weighted irradiance              — diffuse environment lighting
//   9. Subsurface scattering approximation      — light penetration effect
//  10. Procedural foam                          — steepness + shoreline + objects
//  11. ACES filmic tone mapping                  — cinematic HDR→LDR curve
//  12. Depth-based colour falloff               — clear → deep gradient
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 1 — Fresnel Effect & Schlick Approximation
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The Fresnel effect describes how the reflectivity of a surface changes
// with the viewing angle.  At normal incidence (looking straight down),
// a surface reflects a small fraction F₀ of incoming light.  At grazing
// angles (looking along the surface), reflectivity approaches 100%.
//
// The exact Fresnel equations (derived from Maxwell's equations) are
// computationally expensive.  Schlick (1995) proposed a brilliant
// approximation that is both cheap and visually indistinguishable:
//
//   F(θ) = F₀ + (1 − F₀) · (1 − cos θ)⁵
//
// Where:
//   F₀  — reflectance at normal incidence (θ = 0°).  For a dielectric
//          material, F₀ is derived from the index of refraction (IOR):
//
//              F₀ = ((n − 1) / (n + 1))²
//
//          For water with n = 1.33:  F₀ ≈ 0.023  (about 2.3% reflection)
//          For glass with n = 1.5:   F₀ ≈ 0.04
//
//          For conductors (metals), F₀ is complex and depends on the
//          complex IOR.  In practice, we use the measured albedo colour.
//
//   θ   — the angle between the view direction and the reflection direction.
//          In the microfacet model, θ is the angle between the half-vector
//          H = normalize(L + V) and the view direction V, i.e., cos θ = H·V.
//
// Why the power of 5?  Schlick found that (1 − cos θ)⁵ fits the exact
// Fresnel equations to within ~1% error for most materials.  The curve
// stays flat near θ = 0° (F ≈ F₀) and rises sharply near θ = 90° (F → 1).
//
// Physical intuition:  At grazing angles, the surface appears as a thin
// film from the light's perspective.  The light has to traverse a very
// long path through the surface layer, making it increasingly likely to
// be reflected rather than transmitted.  This is why you see strong
// reflections on water when looking toward the horizon.
//
// Reference:  Schlick, C. (1995). "An inexpensive BRDF model for
// physically based rendering." Journal of Graphics Tools.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 2 — GGX / Trowbridge-Reitz Normal Distribution Function (NDF)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The microfacet model assumes that a surface is composed of many tiny
// facets (microfacets), each with its own normal m.  The NDF, denoted D(m),
// describes the statistical distribution of these microfacet normals.
//
// GGX (also called Trowbridge-Reitz) is the most widely used NDF:
//
//   α = roughness²                                    (alpha, variance)
//
//   D(N·H) =  α / [ π · ( (N·H)² · (α − 1) + 1 )² ]
//
// Where:
//   N — the macro-surface normal (our analytical Gerstner normal)
//   H — the half-vector:  H = normalize(L + V)
//   α — the "alpha" roughness parameter.  Squaring the user-provided
//       roughness gives a perceptually linear response: small changes
//       in roughness near 0 have a larger visual effect.
//
// What D represents:  D(N·H) is the density of microfacets oriented
// along the half-vector H.  When roughness → 0, α → 0, and D becomes
// a narrow delta function centered at N (all facets aligned = mirror).
// When roughness → 1, α → 1, and D becomes a broad distribution
// (facets scattered in all directions = diffuse).
//
// Why GGX over Beckmann?  GGX has "heavier tails" — it preserves more
// energy at grazing angles.  This produces sharper, more realistic
// specular highlights at low roughness and better matches measured BRDFs.
//
// The denominator structure (quadratic squared) is key:
//   - When N·H = 1 (perfect alignment):  D = α / (π · 1) = α/π
//   - When N·H → 0 (grazing):  D → α / (π · 1) = α/π  (non-zero tail)
//
// Reference:  Trowbridge & Reitz (1975), "Average information reflected
// from a roughened sphere." J. Opt. Soc. Am.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 3 — Smith Geometric Shadowing-Masking (Schlick-GGX)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// Not every microfacet contributes to the reflection.  Some facets are
// shadowed (blocked from the light by neighbouring facets) or occulted
// (hidden from the camera).  The geometric term G estimates the fraction
// of facets that are visible from BOTH the light and the viewer.
//
// The full Smith-GGX formulation separates this into two independent
// visibility functions:
//
//   G = G₁(V) · G₁(L)
//
// where G₁ is the single-direction visibility function.  The exact
// Smith-GGX integral is expensive, so we use the Schlick-GGX
// approximation:
//
//   G₁(X) =  (X·N) / [ (X·N) · (1 − k) + k ]
//
//   k = α / (2 · (roughness + 1)²)  =  roughness² / (2 · (roughness + 1)²)
//
// Where X is either V (view direction) or L (light direction).
//
// Physical meaning:
//   - When roughness → 0, k → 0, and G₁(X) → 1 (no shadowing)
//   - When roughness → 1, k → 0.25, and G₁(X) < 1 (significant shadowing)
//   - When X·N → 0 (grazing), G₁(X) → 0 (facets hidden)
//
// The product G₁(V) · G₁(L) ensures that both the light and the camera
// can "see" the microfacet.  This prevents energy gain at grazing angles
// and ensures the BRDF is energy-conserving.
//
// Reference:  Walter et al. (2007), "Microfacet models for refraction
// through rough surfaces." SIGGRAPH / EGSR.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 4 — Cook-Torrance Specular BRDF
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The Cook-Torrance BRDF combines the three microfacet components into
// a single specular reflection model:
//
//   fₛ(L, V) =  (D(H) · G(V, L) · F(H, V)) / (4 · (N·V))
//
// Where:
//   D(H) — the GGX normal distribution (Equation 2)
//   G(V,L) — the Smith geometric term (Equation 3)
//   F(H,V) — the Schlick Fresnel (Equation 1)
//   4·(N·V) — the geometric foreshortening factor
//
// The denominator 4·(N·V) accounts for the projection of the microfacet
// onto the macro-surface.  It arises from the change of variables when
// integrating over the hemisphere of incoming directions.
//
// Why this works:  The microfacet model assumes that each perfectly
// smooth microfacet acts like a mirror.  Light arriving from direction L
// is reflected toward V only if the microfacet normal H = normalize(L+V).
// The NDF tells us how many such facets exist, G tells us how many are
// visible, and F tells us how much light they reflect.
//
// Energy conservation:  The BRDF is constructed so that the total
// reflected energy never exceeds the incoming energy.  This is guaranteed
// by the geometric term G and the Fresnel term F (since F ∈ [F₀, 1]
// and the transmitted fraction is 1 − F).
//
// Reference:  Cook & Torrance (1982), "A model for reflection from
// rough surfaces." SIGGRAPH.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 5 — Energy-Conserving Diffuse (Lambert with Fresnel partition)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The diffuse component models light that penetrates the surface, scatters
// subsurface, and exits in a random direction (Lambertian scattering).
//
//   fₔ = (1 − F) · (1 − metalness) · albedo / π
//
// Where:
//   (1 − F) — the fraction of light NOT reflected specularly.  This light
//             enters the surface and is available for diffuse scattering.
//   (1 − metalness) — for dielectrics (metalness=0), full diffuse.
//                     for metals (metalness=1), no diffuse (absorbed).
//   albedo — the base colour of the material (water colour in our case)
//   / π — normalizes the Lambertian lobe so the hemispherical integral
//         equals exactly 1.0 (energy conservation)
//
// For water specifically:  water is a dielectric (metalness = 0), so the
// full (1 − F) fraction is available for the diffuse term.  At normal
// incidence, F ≈ 0.023, so ~97.7% of light enters the water and can
// scatter diffusely.  At grazing angles, F → 1, so the diffuse term
// vanishes — this is why water looks like a mirror at the horizon.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 6 — HDR Environment Map Reflections (Prefiltered)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// For the specular environment contribution, we integrate the BRDF over
// the hemisphere of incoming directions:
//
//   Loₑₙᵥ = ∫ fₛ(L, V) · Lₑₙᵥ(L) · (N·L) dω
//
// This integral is intractable at runtime for arbitrary environment maps.
// The solution (by Epic Games / UE4) is PMREM:
//
//   PMREM (Pre-filtered Multi-Resolution Environment Map) pre-convolves
//   the source HDR environment into a mip chain where each mip level
//   represents the integral of a GGX lobe at a specific roughness:
//
//     MIP(level) = ∫ R · Dₐₗₚₕₐ(level)(R · H) · (N·R) dω
//
//   where α(level) increases with the mip level.  At mip 0 (roughness=0),
//   the map is the original HDR environment.  At higher mips, the map is
//   progressively blurred.
//
// At runtime, we select the mip level based on roughness:
//
//     lod = roughness · maxMipLevel
//     envColor = textureLod(uEnvMap, R, lod)
//
// where R = reflect(-V, N) = -V + 2·(N·V)·N is the perfect mirror
// reflection direction.
//
// Three.js PMREMGenerator performs this pre-filtering automatically from
// a CubeTexture or Scene, producing a CubeTexture with the correct mip
// chain for GGX roughness integration.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 7 — BRDF Integration (Precomputed or Analytical)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The full environment integral also depends on the Fresnel term F, which
// varies with the viewing angle.  To handle this, we separate the integral
// using the Schlick Fresnel form:
//
//   ∫ F(H,V) · Lₑₙᵥ(H) · (N·H) dω
//   = F₀ · ∫ (1-F₀) · L · (N·H) dω  +  ∫ F₀ · L · (N·H) dω
//   = (1-F₀) · ∫ L · (N·H) dω  +  F₀ · ∫ L · (N·H) dω
//
// The two integrals depend only on (N·V) and roughness α, so they can be
// precomputed into a 2D lookup texture (the BRDF LUT):
//
//   BRDF_LUT[NdotV][roughness] = (integral, scale)
//
// Then:
//   Loₑₙᵥ = envColor · (BRDF_scale · F₀ + BRDF_integral)
//
// When a BRDF LUT is not available, we use the closed-form approximation:
//
//   perceptualRoughness = (1 − N·V)⁵
//   scale = perceptualRoughness · (1 − F₀)
//   integral = F₀
//
// This is less accurate but requires no texture lookup.
//
// Reference:  Epic Games, "Moving Frostbite to PBR"
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 8 — Fresnel-Weighted Irradiance (Diffuse Environment)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The diffuse component also needs environment lighting.  For a perfect
// Lambertian surface, the irradiance from an environment map is:
//
//   E = ∫ Lₑₙᵥ(L) · (N·L) dω
//
// This can be precomputed into spherical harmonics (SH) coefficients,
// which allow O(1) evaluation at any normal direction.  Three.js provides
// PMREMGenerator which can generate an irradiance CubeTexture.
//
// The Fresnel-weighted diffuse environment is:
//
//   Loₔ = (1 − F(N,V)) · irradiance(N)
//
// where F(N,V) uses the Schlick approximation with cosθ = N·V (not H·V).
// This ensures that at grazing angles, the diffuse contribution vanishes
// (all light is reflected specularly).
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 9 — Subsurface Scattering Approximation
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// Water is partially transparent.  Light that enters the surface can
// scatter beneath the surface and exit nearby, creating a characteristic
// translucent glow.  Full subsurface scattering is expensive, so we use
// a screen-space approximation:
//
//   SSS = sssColor · max(0.0, dot(V, T)) · (1.0 − F(N,V)) · wrapLight
//
// Where:
//   T — the tangent vector (perpendicular to the wave normal, along the
//       wave crest).  This biases the SSS effect along the surface.
//   wrapLight — a wrapped diffuse term:  max(0, (N·L + 0.33) / 1.33)
//   (1 − F) — SSS only matters when light enters the surface
//
// This creates a subtle rim-lighting effect that simulates light
// penetrating the water surface and scattering beneath it.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 10 — ACES Filmic Tone Mapping
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// HDR colour values (which can exceed 1.0) must be mapped to the LDR
// range [0, 1] for display.  ACES (Academy Color Encoding System) is
// the industry-standard filmic tone mapping curve:
//
//   Cₐₜₛ = (C · (2.51 · C + 0.03)) / (C · (2.43 · C + 0.59) + 0.14)
//
// This S-shaped curve preserves highlights better than Reinhard
// (C / (C + 1)) while maintaining a natural contrast roll-off.  It was
// developed by the Academy of Motion Picture Arts and Sciences.
//
// Reference:  Burley & Borshukov (2014), "An Analytic Model for
// Phase One's Tone Reproduction Preview."
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 11 — Procedural Foam Generation
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// Foam is computed from four independent factors, each producing a value
// in [0, 1].  The final foam alpha is the maximum of all factors,
// modulated by procedural noise for organic breakup.
//
// ━─ Factor 1: Wave Steepness (crest foam) ━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// Foam forms at wave crests where the surface gradient is steepest.
// The vertical gradient magnitude |∇y| is computed analytically in the
// vertex shader:
//
//   For a single Gerstner wave with displacement y = A·cos(φ):
//
//     ∂y/∂x₀ = -A · k · dₓ · sin(φ)
//     ∂y/∂z₀ = -A · k · d_z · sin(φ)
//
//   The gradient magnitude for this wave:
//
//     |∇y|_i = sqrt( (∂y/∂x₀)² + (∂y/∂z₀)² )
//            = A · k · |sin(φ)| · sqrt(dₓ² + d_z²)
//            = A · k · |sin(φ)|          (since d is unit length)
//
//   For N superimposed waves, we sum the absolute contributions:
//
//     |∇y| = Σᵢ Aᵢ · kᵢ · |sin(φᵢ)|
//
//   This gives a scalar that peaks at wave crests (where |sin(φ)| ≈ 1)
//   and drops to zero at troughs (where |sin(φ)| ≈ 0).
//
//   The foam contribution from steepness:
//
//     foam_steep = smoothstep(threshold, threshold + 1/sharpness, |∇y|)
//
//   The smoothstep ensures foam only appears when the gradient exceeds
//   a threshold, with a sharp transition controlled by the sharpness
//   parameter.
//
// ━─ Factor 2: Crest Elevation ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// Foam also correlates with elevation: the highest points of compound
// waves (where multiple crests align) are most likely to break.
//
//   foam_crest = smoothstep(crestMin, crestMax, elevation)
//
//   We use a high threshold so only the top ~10% of wave heights
//   produce foam.  This is combined multiplicatively with steepness
//   so foam only appears at HIGH AND STEEP locations.
//
// ━─ Factor 3: Shoreline Foam ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// When waves approach a shore (the edge of the mesh), they break and
// create a band of white foam.  We compute the distance from the mesh
// boundary:
//
//     halfSize = mesh_size / 2
//     distX = halfSize - |worldX|
//     distZ = halfSize - |worldZ|
//     distEdge = min(distX, distZ)
//
//   Foam appears when distEdge < shorelineFoamWidth:
//
//     foam_shore = 1.0 - smoothstep(0.0, shorelineFoamWidth, distEdge)
//
//   This creates a smooth band of foam along all four edges of the
//   mesh, fading to zero as you move inland.
//
// ━─ Factor 4: Object Intersection Foam ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// When waves hit an object (a pier, a boat, a rock), foam accumulates
// around the base.  For each foam source at position (ox, oz) with
// radius r and foam spread width w:
//
//     d = sqrt( (worldX - ox)² + (worldZ - oz)² )
//     foam_obj_i = 1.0 - smoothstep(r, r + w, d)
//
//   This creates a ring of foam just outside the object boundary,
//   fading to zero at distance r + w.
//
//   Multiple sources are combined with max():
//
//     foam_object = max_i(foam_obj_i)
//
// ━─ Noise Modulation ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// Raw foam from the factors above is too uniform.  Real foam has an
// organic, broken-up appearance.  We use a hash-based noise function
// to create spatial variation:
//
//     noise = hash2D(worldXZ * noiseFrequency + noiseSeed)
//
//   The noise value in [0, 1] is used to attenuate foam:
//
//     foam_final = foam_base * (0.5 + 0.5 * noise)
//
//   This ensures foam is never completely eliminated (minimum 0.5x)
//   but can be doubled in noisy regions, creating a scattered pattern.
//
// ━─ Final Foam Composition ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
//   foam_base = max( foam_steep * foam_crest,  foam_shore,  foam_object )
//   foam_final = clamp( foam_base * noise_modulation, 0, foamMaxOpacity )
//
//   The final colour blends between the water colour and foam colour:
//
//     color = mix(waterColor, foamColor, foam_final)
//
//   Using mix() ensures foam replaces the water colour rather than
//   adding to it, which would break energy conservation.

const fragmentShader = /* glsl */ `
  precision highp float;

  uniform float uTime;

  varying vec3 vWorldPosition;
  varying vec3 vNormal;
  varying float vElevation;
  varying float vWaveGradient;

  // ── PBR uniforms ──────────────────────────────────────────────────────
  uniform float uRoughness;
  uniform float uMetalness;
  uniform vec3  uF0;              // base reflectance (dielectric Fresnel)
  uniform vec3  uLightDir;        // directional light direction (world space)
  uniform vec3  uLightColor;      // directional light colour (HDR)
  uniform samplerCube uEnvMap;    // PMREM-processed environment map
  uniform samplerCube uIrradianceMap;  // irradiance for diffuse env
  uniform sampler2D uBRDFLUT;     // precomputed BRDF lookup (optional)
  uniform int uDebugMode;

  // ── Water appearance uniforms ─────────────────────────────────────────
  uniform vec3  uDeepColor;
  uniform vec3  uShallowColor;
  uniform vec3  uFoamColor;
  uniform vec3  uSSSColor;
  uniform float uSSSScale;

  // ── Foam uniforms ─────────────────────────────────────────────────────
  uniform float uFoamSteepnessThreshold;
  uniform float uFoamSteepnessSharpness;
  uniform float uShorelineFoamWidth;
  uniform float uShorelineFoamOpacity;
  uniform float uFoamNoiseSeed;
  uniform float uFoamNoiseFrequency;
  uniform float uFoamMaxOpacity;
  uniform float uMeshHalfSize;
  uniform float uMaxWaveHeight;
  uniform int   uShorelineSourceCount;
  uniform vec4  uShorelineSources[${MAX_SHORELINE_SOURCES}];  // (x, z, radius, foamWidth)
  uniform int   uFoamSourceCount;
  uniform vec4  uFoamSources[${MAX_FOAM_SOURCES}];  // (x, z, radius, foamWidth)

  // ── Constants ─────────────────────────────────────────────────────────
  const float PI = 3.141592653589793;

  // ───────────────────────────────────────────────────────────────────────
  // Hash / Noise functions for organic foam breakup
  // ───────────────────────────────────────────────────────────────────────

  // 2D hash function — produces a pseudo-random value in [0, 1]
  // based on the input coordinates.  Uses a simple Sobol-style hash.
  float hash2D(vec2 co) {
    return fract(sin(dot(co, vec2(127.1, 311.7))) * 43758.5453);
  }

  // Value noise with multiple octaves for natural-looking foam patterns.
  // Returns a value in [0, 1].
  float foamNoise(vec2 uv) {
    vec2 i = floor(uv);
    vec2 f = fract(uv);

    // Smoothstep interpolation for C1 continuity
    vec2 u = f * f * (3.0 - 2.0 * f);

    // Sample the hash at the four corners and interpolate
    float a = hash2D(i);
    float b = hash2D(i + vec2(1.0, 0.0));
    float c = hash2D(i + vec2(0.0, 1.0));
    float d = hash2D(i + vec2(1.0, 1.0));

    return mix(
      mix(a, b, u.x),
      mix(c, d, u.x),
      u.y
    );
  }

  float foamFBM(vec2 uv) {
    float value = 0.0;
    float amp = 0.5;
    float freq = 1.0;

    for (int i = 0; i < 4; i++) {
      value += amp * foamNoise(uv * freq);
      freq *= 2.03;
      amp *= 0.5;
    }

    return value;
  }

  float circularBand(vec2 p, vec2 center, float radius, float width) {
    float d = distance(p, center);
    float insideFade = smoothstep(radius - width * 0.35, radius, d);
    float outsideFade = 1.0 - smoothstep(radius, radius + width, d);
    return insideFade * outsideFade;
  }

  vec3 tonemapACES(vec3 color) {
    color = (color * (2.51 * color + 0.03)) / (color * (2.43 * color + 0.59) + 0.14);
    return pow(max(color, vec3(0.0)), vec3(1.0 / 2.2));
  }

  // ───────────────────────────────────────────────────────────────────────
  // EQUATION 1: Schlick Fresnel Approximation
  // F(θ) = F₀ + (1 − F₀) · (1 − cos θ)⁵
  // ───────────────────────────────────────────────────────────────────────
  vec3 fresnelSchlick(float cosTheta, vec3 F0) {
    return F0 + (1.0 - F0) * pow(1.0 - cosTheta, 5.0);
  }

  // ───────────────────────────────────────────────────────────────────────
  // EQUATION 2: GGX / Trowbridge-Reitz Normal Distribution Function
  // D = α² / ( π · ( (N·H)² · (α² − 1) + 1 )² )
  // ───────────────────────────────────────────────────────────────────────
  float distributionGGX(float NdotH, float roughness) {
    float a   = roughness * roughness;
    float a2  = a * a;
    float d   = NdotH * NdotH * (a2 - 1.0) + 1.0;
    return a2 / (PI * d * d);
  }

  // ───────────────────────────────────────────────────────────────────────
  // EQUATION 3: Smith Geometric Shadowing (Schlick-GGX approximation)
  // G₁(X) =  (X·N) / ( (X·N) · (1 − k) + k )
  // k = roughness² / (2 · (roughness + 1)²)
  // G  =  G₁(V) · G₁(L)
  // ───────────────────────────────────────────────────────────────────────
  float geometrySchlickGGX(float NdotX, float roughness) {
    float r = roughness + 1.0;
    float k = (roughness * roughness) / (r * r);
    return NdotX / (NdotX * (1.0 - k) + k);
  }

  float geometrySmith(float NdotV, float NdotL, float roughness) {
    return geometrySchlickGGX(NdotV, roughness) *
           geometrySchlickGGX(NdotL, roughness);
  }

  // ───────────────────────────────────────────────────────────────────────
  // EQUATION 7: BRDF Integration (analytical fallback)
  // ───────────────────────────────────────────────────────────────────────
  vec3 brdfIntegrationAnalytical(float NdotV, vec3 F0) {
    float perceptualRoughness = pow(1.0 - NdotV, 5.0);
    return perceptualRoughness * (1.0 - F0) + F0;
  }

  void main() {
    // ── Surface normal (analytical Gerstner) ────────────────────────────
    vec3 N = normalize(vNormal);

    if (uDebugMode == 2) {
      gl_FragColor = vec4(N * 0.5 + 0.5, 1.0);
      return;
    }

    if (uDebugMode == 3) {
      float e = clamp(vElevation / max(uMaxWaveHeight, 0.001) * 0.5 + 0.5, 0.0, 1.0);
      gl_FragColor = vec4(vec3(e), 1.0);
      return;
    }

    if (uDebugMode == 4) {
      float s = clamp(vWaveGradient / max(uFoamSteepnessThreshold * 2.0, 0.001), 0.0, 1.0);
      gl_FragColor = vec4(vec3(s), 1.0);
      return;
    }

    // ── View direction ──────────────────────────────────────────────────
    vec3 V = normalize(cameraPosition - vWorldPosition);

    // ── Light direction (uniform, already normalised on JS side) ────────
    vec3 L = normalize(uLightDir);
    vec3 H = normalize(V + L);                       // half-vector

    float NdotV = max(dot(N, V), 0.001);  // avoid division by zero
    float NdotL = max(dot(N, L), 0.0);
    float NdotH = max(dot(N, H), 0.0);
    float HdotV = max(dot(H, V), 0.0);

    // ── EQUATION 1: Fresnel (Schlick) ───────────────────────────────────
    vec3 F = fresnelSchlick(HdotV, uF0);

    // ── EQUATION 2: Normal Distribution Function (GGX) ──────────────────
    float D = distributionGGX(NdotH, uRoughness);

    // ── EQUATION 3: Geometric Shadowing (Smith) ─────────────────────────
    float G = geometrySmith(NdotV, NdotL, uRoughness);

    // ── EQUATION 4: Cook-Torrance specular BRDF ─────────────────────────
    vec3 kSpec = vec3(0.0);
    if (NdotL > 0.0) {
      float specDenom = max(4.0 * NdotV * NdotL, 0.001);
      kSpec = (D * G * F) / specDenom;
    }

    // ── EQUATION 5: Diffuse albedo with energy conservation ─────────────
    float t = smoothstep(-4.0, 4.0, vElevation);
    vec3 albedo = mix(uDeepColor, uShallowColor, t);
    vec3 kDiff = (1.0 - F) * (1.0 - uMetalness) * albedo / PI;

    // ── Direct lighting ─────────────────────────────────────────────────
    vec3 directLighting = (kSpec + kDiff) * uLightColor * NdotL;

    // ── EQUATION 6: Environment map reflection (prefiltered) ────────────
    vec3 R = reflect(-V, N);
    float envMapRoughness = uRoughness;
    vec3 envColor = textureLod(uEnvMap, R, envMapRoughness * 4.0).rgb;

    // ── EQUATION 7: BRDF Integration ────────────────────────────────────
    vec3 brdfFactor;
    #ifdef USE_BRDF_LUT
      vec2 brdfUV = vec2(NdotV, uRoughness);
      vec2 brdf = texture(uBRDFLUT, brdfUV).rg;
      brdfFactor = uF0 * brdf.x + brdf.y;
    #else
      brdfFactor = brdfIntegrationAnalytical(NdotV, uF0);
    #endif

    vec3 envSpecular = envColor * brdfFactor;

    // ── EQUATION 8: Fresnel-weighted irradiance (diffuse env) ───────────
    vec3 irradiance = texture(uIrradianceMap, N).rgb;
    vec3 F_diffuse = fresnelSchlick(NdotV, uF0);
    vec3 envDiffuse = (1.0 - F_diffuse) * irradiance * albedo;

    // ── EQUATION 9: Subsurface scattering approximation ─────────────────
    vec3 T = normalize(V - N * dot(V, N));
    float wrapLight = max(0.0, dot(N, L) * 0.5 + 0.5);
    float sss = max(0.0, dot(V, T)) * (1.0 - F_diffuse.r) * wrapLight;
    vec3 sssContribution = uSSSColor * sss * uSSSScale * 0.0625;

    // ── Combine water contributions (before foam) ───────────────────────
    vec3 waterColor = directLighting + envSpecular + envDiffuse + sssContribution;

    if (uDebugMode == 1) {
      gl_FragColor = vec4(tonemapACES(waterColor), 1.0);
      return;
    }

    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    // EQUATION 11: Procedural Foam Generation
    // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    // ━─ Factor 1: Wave steepness ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    //
    // The vertex shader computes |∇y| from the summed Gerstner height
    // derivatives. Large values mean a locally steep/breaking surface.
    float foamSteep = smoothstep(
      uFoamSteepnessThreshold,
      uFoamSteepnessThreshold + (1.0 / uFoamSteepnessSharpness),
      vWaveGradient
    );

    // ━─ Factor 2: Crest elevation ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    //
    // Normalise elevation by the sum of amplitudes. This keeps foam stable
    // if the wave set changes scale.
    float crestHeight = clamp(vElevation / max(uMaxWaveHeight, 0.001), 0.0, 1.0);
    float foamCrest = smoothstep(0.45, 0.78, crestHeight);

    // Crest foam favours high water that is also steep. Very steep water
    // can still produce sparse breaking foam even slightly below the crest.
    float foamCrests = foamCrest * (0.35 + 0.65 * foamSteep);
    float foamBreaking = pow(foamSteep, 3.0) * 0.45;
    float foamCrestDebug = max(foamCrests, foamBreaking);

    // ━─ Factor 3: Shoreline foam ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    //
    // Distance from the mesh boundary plus optional circular shoreline
    // fields for islands/sandbars.
    float foamShore = 0.0;
    if (uShorelineFoamWidth > 0.0) {
      vec2 absPos = abs(vWorldPosition.xz);
      float distX = uMeshHalfSize - absPos.x;
      float distZ = uMeshHalfSize - absPos.z;
      float distEdge = min(distX, distZ);
      foamShore = (1.0 - smoothstep(0.0, uShorelineFoamWidth, distEdge))
                  * uShorelineFoamOpacity;
    }

    for (int i = 0; i < ${MAX_SHORELINE_SOURCES}; i++) {
      if (i >= uShorelineSourceCount) break;

      vec4 src = uShorelineSources[i];
      float band = circularBand(vWorldPosition.xz, src.xy, src.z, src.w);
      foamShore = max(foamShore, band * uShorelineFoamOpacity);
    }

    // ━─ Factor 4: Object Intersection Foam ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    //
    // For each foam source, compute distance and create a ring of foam
    // just outside the object boundary.
    float foamObject = 0.0;
    for (int i = 0; i < ${MAX_FOAM_SOURCES}; i++) {
      if (i >= uFoamSourceCount) break;

      vec4 src = uFoamSources[i];
      foamObject = max(
        foamObject,
        circularBand(vWorldPosition.xz, src.xy, src.z, src.w)
      );
    }

    // ━─ Compose foam factors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    //
    // Take the maximum of all independent foam sources.
    // This ensures the strongest foam signal wins at each pixel.
    float foamBase = max(max(foamCrests, foamBreaking), max(foamShore, foamObject));

    // ━─ Noise Modulation ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    //
    // Domain-warped fBM breaks up the analytical masks without requiring
    // a painted foam texture.
    vec2 windDrift = normalize(vec2(0.8, 0.35)) * uTime * 0.08;
    vec2 foamUV = vWorldPosition.xz * uFoamNoiseFrequency * 0.08 + windDrift;
    foamUV += vec2(uFoamNoiseSeed, uFoamNoiseSeed * 1.37);

    vec2 warp = vec2(
      foamFBM(foamUV + 17.0),
      foamFBM(foamUV - 29.0)
    ) - 0.5;

    float breakup = foamFBM(foamUV + warp * 1.75);
    float lace = smoothstep(0.28, 0.86, breakup);

    // Strong masks remain continuous; weak masks become broken, lacy foam.
    float noiseMod = mix(0.25 + 0.75 * lace, 1.0, smoothstep(0.65, 1.0, foamBase));
    float foamFinal = foamBase * noiseMod;

    // Clamp to maximum opacity
    foamFinal = clamp(foamFinal, 0.0, uFoamMaxOpacity);

    if (uDebugMode == 5) {
      gl_FragColor = vec4(vec3(clamp(foamCrestDebug, 0.0, 1.0)), 1.0);
      return;
    }

    if (uDebugMode == 6) {
      gl_FragColor = vec4(vec3(clamp(foamShore, 0.0, 1.0)), 1.0);
      return;
    }

    if (uDebugMode == 7) {
      gl_FragColor = vec4(vec3(clamp(foamObject, 0.0, 1.0)), 1.0);
      return;
    }

    if (uDebugMode == 8) {
      gl_FragColor = vec4(vec3(foamFinal), 1.0);
      return;
    }

    // ━─ Apply foam to colour ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    //
    // Blend between water colour and foam colour.  Using mix() ensures
    // foam replaces the water colour rather than adding to it.
    vec3 color = mix(waterColor, uFoamColor, foamFinal);

    gl_FragColor = vec4(tonemapACES(color), 1.0);
  }
`;

// ---------------------------------------------------------------------------
// Helper: normalize a 2D direction and pack wave config into arrays
// ---------------------------------------------------------------------------

function normalizeDirection2(d: [number, number]): [number, number] {
  const len = Math.sqrt(d[0] * d[0] + d[1] * d[1]);
  if (len === 0) return [1, 0];
  return [d[0] / len, d[1] / len];
}

// ---------------------------------------------------------------------------
// WaterMesh class
// ---------------------------------------------------------------------------

export class WaterMesh extends Mesh<BufferGeometry, ShaderMaterial> {
  private _timeUniform: { value: number };
  private _debugModeUniform: { value: number };

  constructor(config: Partial<WaterMeshConfig> = {}) {
    const resolved: WaterMeshConfig = { ...defaultConfig, ...config };
    const waves = resolved.waves;

    // -- Geometry ----------------------------------------------------------
    const geometry = new PlaneGeometry(
      resolved.size,
      resolved.size,
      resolved.segments,
      resolved.segments
    );
    geometry.rotateX(-Math.PI / 2);

    // -- Prepare uniform arrays --------------------------------------------
    const waveCount = Math.min(waves.length, MAX_WAVES);

    const amplitudeArr: number[] = [];
    const wavelengthArr: number[] = [];
    const speedArr: number[] = [];
    const directionArr: number[] = []; // interleaved dx, dz
    const steepnessArr: number[] = [];
    let maxWaveHeight = 0;

    for (let i = 0; i < waveCount; i++) {
      const w = waves[i];
      const [dx, dz] = normalizeDirection2(w.direction);

      amplitudeArr.push(w.amplitude);
      wavelengthArr.push(w.wavelength);
      speedArr.push(w.speed);
      directionArr.push(dx, dz);
      steepnessArr.push(w.steepness);
      maxWaveHeight += Math.abs(w.amplitude);
    }

    // Pad to MAX_WAVES with zeros
    while (amplitudeArr.length < MAX_WAVES) {
      amplitudeArr.push(0);
      wavelengthArr.push(1);
      speedArr.push(0);
      directionArr.push(1, 0);
      steepnessArr.push(0);
    }

    // -- PBR parameters ----------------------------------------------------
    const ior = resolved.ior ?? 1.33;
    const f0Scalar = ((ior - 1) / (ior + 1)) ** 2;
    const f0 = [f0Scalar, f0Scalar, f0Scalar];

    const roughness = resolved.roughness ?? 0.15;
    const metalness = resolved.metalness ?? 0.0;

    // -- Shoreline / object foam source arrays -----------------------------
    const shorelineSources = resolved.shorelineFoamSources ?? [];
    const shorelineSourceCount = Math.min(
      shorelineSources.length,
      MAX_SHORELINE_SOURCES
    );

    const shorelineSourceArr: Vector4[] = [];
    for (let i = 0; i < shorelineSourceCount; i++) {
      const src = shorelineSources[i];
      shorelineSourceArr.push(new Vector4(src[0], src[1], src[2], src[3]));
    }
    while (shorelineSourceArr.length < MAX_SHORELINE_SOURCES) {
      shorelineSourceArr.push(new Vector4(0, 0, 0, 0));
    }

    const foamSources = resolved.objectFoamSources ?? [];
    const foamSourceCount = Math.min(foamSources.length, MAX_FOAM_SOURCES);

    const foamSourceArr: Vector4[] = [];
    for (let i = 0; i < foamSourceCount; i++) {
      const src = foamSources[i];
      foamSourceArr.push(new Vector4(src[0], src[1], src[2], src[3]));
    }
    while (foamSourceArr.length < MAX_FOAM_SOURCES) {
      foamSourceArr.push(new Vector4(0, 0, 0, 0));
    }

    // -- Material ----------------------------------------------------------
    const material = new ShaderMaterial({
      vertexShader,
      fragmentShader,
      uniforms: {
        uTime: { value: 0 },
        uWaveCount: { value: waveCount },
        uAmplitude: { value: amplitudeArr },
        uWavelength: { value: wavelengthArr },
        uSpeed: { value: speedArr },
        uDirection: { value: directionArr },
        uSteepness: { value: steepnessArr },
        uMaxWaveHeight: { value: Math.max(maxWaveHeight, 0.001) },

        // PBR uniforms
        uRoughness: { value: roughness },
        uMetalness: { value: metalness },
        uF0: { value: new Vector3(...f0) },
        uLightDir: { value: new Vector3(0.5, 1.0, 0.3).normalize() },
        uLightColor: { value: new Vector3(1.5, 1.3, 1.0) },
        uEnvMap: { value: resolved.envMap || null },
        uIrradianceMap: { value: resolved.irradianceMap || null },
        uBRDFLUT: { value: resolved.brdfLUT || null },
        uDebugMode: { value: 0 },

        // Water appearance uniforms
        uDeepColor: {
          value: new Vector3(
            ...(resolved.deepColor ?? [0.0, 0.05, 0.15])
          ),
        },
        uShallowColor: {
          value: new Vector3(
            ...(resolved.shallowColor ?? [0.0, 0.5, 0.6])
          ),
        },
        uFoamColor: {
          value: new Vector3(...(resolved.foamColor ?? [0.95, 0.95, 0.95])),
        },
        uSSSColor: {
          value: new Vector3(...(resolved.sssColor ?? [0.0, 0.35, 0.45])),
        },
        uSSSScale: { value: resolved.sssScale ?? 8.0 },

        // Foam uniforms
        uFoamSteepnessThreshold: {
          value: resolved.foamSteepnessThreshold ?? 0.3,
        },
        uFoamSteepnessSharpness: {
          value: resolved.foamSteepnessSharpness ?? 8.0,
        },
        uShorelineFoamWidth: {
          value: resolved.shorelineFoamWidth ?? 8.0,
        },
        uShorelineFoamOpacity: {
          value: resolved.shorelineFoamOpacity ?? 0.6,
        },
        uFoamNoiseSeed: {
          value: resolved.foamNoiseSeed ?? 42.0,
        },
        uFoamNoiseFrequency: {
          value: resolved.foamNoiseFrequency ?? 3.0,
        },
        uFoamMaxOpacity: {
          value: resolved.foamMaxOpacity ?? 0.7,
        },
        uMeshHalfSize: { value: resolved.size / 2 },
        uShorelineSourceCount: { value: shorelineSourceCount },
        uShorelineSources: { value: shorelineSourceArr },
        uFoamSourceCount: { value: foamSourceCount },
        uFoamSources: { value: foamSourceArr },
      },
      side: DoubleSide,
      lights: false, // We handle lighting manually in the shader
    });

    super(geometry, material);

    this._timeUniform = material.uniforms.uTime;
    this._debugModeUniform = material.uniforms.uDebugMode;

    // Y = 0 is the water surface.
    this.position.y = 0;
  }

  /**
   * Call every frame to advance the wave animation.
   */
  update(time: number): void {
    this._timeUniform.value = time;
  }

  setDebugMode(mode: number): void {
    this._debugModeUniform.value = mode;
  }
}
