import {
  BufferGeometry,
  DoubleSide,
  PlaneGeometry,
  ShaderMaterial,
  Mesh,
  Vector3,
  Texture,
} from 'three';

// ---------------------------------------------------------------------------
// Wave configuration
// ---------------------------------------------------------------------------

/**
 * Parameters for a single Gerstner wave layer.
 *
 * - `amplitude`: Peak displacement from rest level (meters).
 * - `wavelength`: Distance between successive crests (meters).
 * - `speed`: Propagation speed (meters/second).
 * - `direction`: 2D unit vector `(dx, dz)` on the XZ plane.
 * - `steepness`: Shape parameter `q ∈ [0, 1]`.  `0` degenerates to a
 *   linear sine wave; values near `1` produce sharp, trochoidal crests.
 */
export interface GerstnerWaveConfig {
  amplitude: number;
  wavelength: number;
  speed: number;
  direction: [number, number];
  steepness: number;
}

/**
 * Configuration for the ocean mesh.
 */
export interface WaterMeshConfig {
  size: number;
  segments: number;
  waves: GerstnerWaveConfig[];

  /**
   * HDR environment map generated by PMREMGenerator.
   * Used for physically based reflections.
   */
  envMap?: Texture | null;

  /**
   * Spherical harmonic irradiance map for diffuse environment lighting.
   * When omitted, the shader falls back to a simple ambient term.
   */
  irradianceMap?: Texture | null;

  /**
   * Precomputed BRDF lookup texture (2D) for integrating the GGX
   * distribution over the environment map.  Generated offline or via
   * a dedicated BRDF shader.  When omitted, a closed-form approximation
   * is used in the shader.
   */
  brdfLUT?: Texture | null;

  /**
   * Surface roughness for the GGX distribution.
   * `0` = mirror-smooth, `1` = completely diffuse.
   * Water is typically 0.1–0.4 depending on wind.
   */
  roughness?: number;

  /**
   * Metalness factor.  Water is a dielectric so this stays `0`.
   * Kept for material compatibility with the standard PBR workflow.
   */
  metalness?: number;

  /**
   * Index of refraction for the Fresnel calculation.
   * Water ≈ 1.33, but can be tweaked for artistic effect.
   */
  ior?: number;

  /**
   * Deep water colour (troughs).
   */
  deepColor?: [number, number, number];

  /**
   * Shallow / surface colour (crests).
   */
  shallowColor?: [number, number, number];

  /**
   * Foam colour applied at wave crests.
   */
  foamColor?: [number, number, number];

  /**
   * Threshold (in elevation space) above which foam appears.
   */
  foamThreshold?: number;

  /**
   * Divergence threshold for wave-breaking detection.
   * When the accumulated horizontal velocity divergence exceeds this
   * value, foam is generated.  Higher values mean less breaking foam.
   * Typical range: 0.01 – 0.2.
   */
  foamBreakingThreshold?: number;

  /**
   * Spatial frequency of the procedural foam noise.
   * Larger values produce smaller, denser foam cells.
   * Typical range: 2 – 20.
   */
  foamNoiseScale?: number;

  /**
   * Drift speed of the foam noise pattern (world units/sec).
   * Creates the illusion of foam being advected by currents.
   * Typical range: 0.5 – 5.
   */
  foamNoiseDrift?: number;

  /**
   * Distance to the nearest shoreline (world units).
   * When set, foam accumulates within `shoreFoamWidth` meters of
   * the shore boundary.  Omit or set to Infinity to disable.
   */
  shoreDistance?: number;

  /**
   * Width of the foam band along the shoreline.
   */
  shoreFoamWidth?: number;

  /**
   * Subsurface scattering approximation colour.
   * Simulates light that penetrates the surface and exits nearby.
   */
  sssColor?: [number, number, number];

  /**
   * Scale of the SSS effect.  Larger values let light penetrate deeper.
   */
  sssScale?: number;
}

const defaultConfig: WaterMeshConfig = {
  size: 1000,
  segments: 256,
  roughness: 0.15,
  metalness: 0.0,
  ior: 1.33,
  deepColor: [0.0, 0.05, 0.15],
  shallowColor: [0.0, 0.5, 0.6],
  foamColor: [0.95, 0.95, 0.95],
  foamThreshold: 2.5,
  foamBreakingThreshold: 0.08,
  foamNoiseScale: 8.0,
  foamNoiseDrift: 2.0,
  shoreDistance: Infinity,
  shoreFoamWidth: 3.0,
  sssColor: [0.0, 0.35, 0.45],
  sssScale: 8.0,
  waves: [
    {
      amplitude: 2.0,
      wavelength: 40.0,
      speed: 12.0,
      direction: [1, 0.3],
      steepness: 0.4,
    },
    {
      amplitude: 1.0,
      wavelength: 12.0,
      speed: 6.0,
      direction: [0.5, 1],
      steepness: 0.5,
    },
    {
      amplitude: 0.5,
      wavelength: 5.0,
      speed: 3.0,
      direction: [-1, 0.7],
      steepness: 0.6,
    },
  ],
};

// ---------------------------------------------------------------------------
// GLSL constants
// ---------------------------------------------------------------------------

const MAX_WAVES = 8;

// ---------------------------------------------------------------------------
// Vertex shader
// ---------------------------------------------------------------------------
//
// Gerstner wave displacement — entirely in the vertex shader.
//
// For each wave layer i with parameters (A, q, λ, v, d):
//
//   k  = 2π / λ                          (wavenumber)
//   ω  = k * v                           (angular frequency)
//   φ  = k · (d · p₀) - ω * t            (phase, p₀ = original xz)
//
//   Displacement:
//     x' = x₀ - A * q * sin(φ) * dₓ
//     y' =  A * cos(φ)
//     z' = z₀ - A * q * sin(φ) * d_z
//
//   Analytical tangent vectors (partial derivatives w.r.t. original position):
//     ∂P/∂x₀ = (1 - A*q*k*dₓ²*cosφ,  -A*k*dₓ*sinφ,  -A*q*k*dₓ*d_z*cosφ)
//     ∂P/∂z₀ = (-A*q*k*dₓ*d_z*cosφ,  -A*k*d_z*sinφ,  1 - A*q*k*d_z²*cosφ)
//
//   Normal = normalize( cross( ∂P/∂x₀ , ∂P/∂z₀ ) )
//
// Multiple layers are accumulated: displacement sums, and tangent
// components sum analytically (chain rule through the shared original
// position p₀).  No numerical finite-difference approximations.

const vertexShader = /* glsl */ `
  uniform float uTime;
  uniform int   uWaveCount;

  // Per-wave parameter arrays
  uniform float uAmplitude[${MAX_WAVES}];
  uniform float uWavelength[${MAX_WAVES}];
  uniform float uSpeed[${MAX_WAVES}];
  uniform vec2  uDirection[${MAX_WAVES}];
  uniform float uSteepness[${MAX_WAVES}];

  varying vec3 vWorldPosition;
  varying vec3 vNormal;
  varying float vElevation;
  varying float vBreaking;       // accumulated wave-breaking divergence

  void main() {
    vec3 p = position;                  // original vertex (y ≈ 0)
    vec2 p0 = p.xz;                     // original xz on the surface

    // Accumulators for analytical tangent vectors
    vec3 tx = vec3(1.0, 0.0, 0.0);     // ∂P/∂x₀  (starts at identity)
    vec3 tz = vec3(0.0, 0.0, 1.0);     // ∂P/∂z₀

    vec3 disp = vec3(0.0);
    float breaking = 0.0;          // wave-breaking divergence accumulator

    for (int i = 0; i < ${MAX_WAVES}; i++) {
      if (i >= uWaveCount) break;

      float A  = uAmplitude[i];
      float q  = uSteepness[i];
      float wl = uWavelength[i];
      float s  = uSpeed[i];
      vec2  d  = normalize(uDirection[i]);

      float k = 2.0 * 3.141592653589793 / wl;   // wavenumber
      float omega = k * s;                         // angular frequency
      float phi = k * dot(p0, d) - omega * uTime; // phase

      float sp = sin(phi);
      float cp = cos(phi);

      // -- Gerstner displacement ------------------------------------------
      disp.x += -A * q * sp * d.x;
      disp.y +=  A * cp;
      disp.z += -A * q * sp * d.y;

       // -- Analytical tangent contributions -------------------------------
       // ∂φ/∂x₀ = k * d.x ,  ∂φ/∂z₀ = k * d.y  (d.y is dz)
       float aqk = A * q * k;

       // -- Wave breaking divergence ----------------------------------------
       // The horizontal velocity of a Gerstner wave is:
       //   v = (A*q*v*dₖ*cos(φ))  in propagation direction d
       // The 2D divergence ∇·v (compression) is:
       //   ∇·v = -A*q*k²*cos(φ)
       // Positive divergence means expansion (troughs), negative means
       // compression (crests).  We accumulate max(0, -div) so that
       // compression zones produce a positive breaking signal.
       // This is the key insight: foam forms where waves compress and break.
       float k2 = k * k;
       breaking += max(0.0, -A * q * k2 * cp);

       tx.x += -aqk * d.x * d.x * cp;
      tx.y += -A * k * d.x * sp;
      tx.z += -aqk * d.x * d.y * cp;

      tz.x += -aqk * d.x * d.y * cp;
      tz.y += -A * k * d.y * sp;
      tz.z += -aqk * d.y * d.y * cp;
    }

    vec3 pos = p + disp;

    // Analytical normal from cross product of tangent vectors
    vec3 normal = normalize(cross(tx, tz));

    vWorldPosition = (modelMatrix * vec4(pos, 1.0)).xyz;
    vNormal = normalize(normalMatrix * normal);
    vElevation = disp.y;
    vBreaking = breaking;

    gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
  }
`;

// ---------------------------------------------------------------------------
// Fragment shader — Full Physically Based Water Rendering
// ---------------------------------------------------------------------------
//
// This shader implements a complete PBR water model built on the
// Cook-Torrance microfacet BRDF with the following components:
//
//   1. Schlick Fresnel approximation          — angle-dependent reflectance
//   2. GGX / Trowbridge-Reitz NDF             — microfacet normal distribution
//   3. Smith geometric shadowing (Schlick-GGX) — visibility / masking term
//   4. Cook-Torrance specular BRDF             — combines D, G, F
//   5. Energy-conserving diffuse                — (1-F) partition, metalness
//   6. HDR environment map reflections          — prefiltered via PMREM
//   7. BRDF integration for rough env maps     — precomputed or analytical
//   8. Fresnel-weighted irradiance              — diffuse environment lighting
//   9. Subsurface scattering approximation      — light penetration effect
//  10. Foam / whitecaps at crests               — elevation-based foam
//  11. ACES filmic tone mapping                  — cinematic HDR→LDR curve
//  12. Depth-based colour falloff               — clear → deep gradient
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 1 — Fresnel Effect & Schlick Approximation
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The Fresnel effect describes how the reflectivity of a surface changes
// with the viewing angle.  At normal incidence (looking straight down),
// a surface reflects a small fraction F₀ of incoming light.  At grazing
// angles (looking along the surface), reflectivity approaches 100%.
//
// The exact Fresnel equations (derived from Maxwell's equations) are
// computationally expensive.  Schlick (1995) proposed a brilliant
// approximation that is both cheap and visually indistinguishable:
//
//   F(θ) = F₀ + (1 − F₀) · (1 − cos θ)⁵
//
// Where:
//   F₀  — reflectance at normal incidence (θ = 0°).  For a dielectric
//          material, F₀ is derived from the index of refraction (IOR):
//
//              F₀ = ((n − 1) / (n + 1))²
//
//          For water with n = 1.33:  F₀ ≈ 0.023  (about 2.3% reflection)
//          For glass with n = 1.5:   F₀ ≈ 0.04
//
//          For conductors (metals), F₀ is complex and depends on the
//          complex IOR.  In practice, we use the measured albedo colour.
//
//   θ   — the angle between the view direction and the reflection direction.
//          In the microfacet model, θ is the angle between the half-vector
//          H = normalize(L + V) and the view direction V, i.e., cos θ = H·V.
//
// Why the power of 5?  Schlick found that (1 − cos θ)⁵ fits the exact
// Fresnel equations to within ~1% error for most materials.  The curve
// stays flat near θ = 0° (F ≈ F₀) and rises sharply near θ = 90° (F → 1).
//
// Physical intuition:  At grazing angles, the surface appears as a thin
// film from the light's perspective.  The light has to traverse a very
// long path through the surface layer, making it increasingly likely to
// be reflected rather than transmitted.  This is why you see strong
// reflections on water when looking toward the horizon.
//
// Reference:  Schlick, C. (1995). "An inexpensive BRDF model for
// physically based rendering." Journal of Graphics Tools.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 2 — GGX / Trowbridge-Reitz Normal Distribution Function (NDF)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The microfacet model assumes that a surface is composed of many tiny
// facets (microfacets), each with its own normal m.  The NDF, denoted D(m),
// describes the statistical distribution of these microfacet normals.
//
// GGX (also called Trowbridge-Reitz) is the most widely used NDF:
//
//   α = roughness²                                    (alpha, variance)
//
//   D(N·H) =  α / [ π · ( (N·H)² · (α − 1) + 1 )² ]
//
// Where:
//   N — the macro-surface normal (our analytical Gerstner normal)
//   H — the half-vector:  H = normalize(L + V)
//   α — the "alpha" roughness parameter.  Squaring the user-provided
//       roughness gives a perceptually linear response: small changes
//       in roughness near 0 have a larger visual effect.
//
// What D represents:  D(N·H) is the density of microfacets oriented
// along the half-vector H.  When roughness → 0, α → 0, and D becomes
// a narrow delta function centered at N (all facets aligned = mirror).
// When roughness → 1, α → 1, and D becomes a broad distribution
// (facets scattered in all directions = diffuse).
//
// Why GGX over Beckmann?  GGX has "heavier tails" — it preserves more
// energy at grazing angles.  This produces sharper, more realistic
// specular highlights at low roughness and better matches measured BRDFs.
//
// The denominator structure (quadratic squared) is key:
//   - When N·H = 1 (perfect alignment):  D = α / (π · 1) = α/π
//   - When N·H → 0 (grazing):  D → α / (π · 1) = α/π  (non-zero tail)
//
// Reference:  Trowbridge & Reitz (1975), "Average information reflected
// from a roughened sphere." J. Opt. Soc. Am.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 3 — Smith Geometric Shadowing-Masking (Schlick-GGX)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// Not every microfacet contributes to the reflection.  Some facets are
// shadowed (blocked from the light by neighbouring facets) or occulted
// (hidden from the camera).  The geometric term G estimates the fraction
// of facets that are visible from BOTH the light and the viewer.
//
// The full Smith-GGX formulation separates this into two independent
// visibility functions:
//
//   G = G₁(V) · G₁(L)
//
// where G₁ is the single-direction visibility function.  The exact
// Smith-GGX integral is expensive, so we use the Schlick-GGX
// approximation:
//
//   G₁(X) =  (X·N) / [ (X·N) · (1 − k) + k ]
//
//   k = α / (2 · (roughness + 1)²)  =  roughness² / (2 · (roughness + 1)²)
//
// Where X is either V (view direction) or L (light direction).
//
// Physical meaning:
//   - When roughness → 0, k → 0, and G₁(X) → 1 (no shadowing)
//   - When roughness → 1, k → 0.25, and G₁(X) < 1 (significant shadowing)
//   - When X·N → 0 (grazing), G₁(X) → 0 (facets hidden)
//
// The product G₁(V) · G₁(L) ensures that both the light and the camera
// can "see" the microfacet.  This prevents energy gain at grazing angles
// and ensures the BRDF is energy-conserving.
//
// Reference:  Walter et al. (2007), "Microfacet models for refraction
// through rough surfaces." SIGGRAPH / EGSR.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 4 — Cook-Torrance Specular BRDF
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The Cook-Torrance BRDF combines the three microfacet components into
// a single specular reflection model:
//
//   fₛ(L, V) =  (D(H) · G(V, L) · F(H, V)) / (4 · (N·V))
//
// Where:
//   D(H) — the GGX normal distribution (Equation 2)
//   G(V,L) — the Smith geometric term (Equation 3)
//   F(H,V) — the Schlick Fresnel (Equation 1)
//   4·(N·V) — the geometric foreshortening factor
//
// The denominator 4·(N·V) accounts for the projection of the microfacet
// onto the macro-surface.  It arises from the change of variables when
// integrating over the hemisphere of incoming directions.
//
// Why this works:  The microfacet model assumes that each perfectly
// smooth microfacet acts like a mirror.  Light arriving from direction L
// is reflected toward V only if the microfacet normal H = normalize(L+V).
// The NDF tells us how many such facets exist, G tells us how many are
// visible, and F tells us how much light they reflect.
//
// Energy conservation:  The BRDF is constructed so that the total
// reflected energy never exceeds the incoming energy.  This is guaranteed
// by the geometric term G and the Fresnel term F (since F ∈ [F₀, 1]
// and the transmitted fraction is 1 − F).
//
// Reference:  Cook & Torrance (1982), "A model for reflection from
// rough surfaces." SIGGRAPH.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 5 — Energy-Conserving Diffuse (Lambert with Fresnel partition)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The diffuse component models light that penetrates the surface, scatters
// subsurface, and exits in a random direction (Lambertian scattering).
//
//   fₔ = (1 − F) · (1 − metalness) · albedo / π
//
// Where:
//   (1 − F) — the fraction of light NOT reflected specularly.  This light
//             enters the surface and is available for diffuse scattering.
//   (1 − metalness) — for dielectrics (metalness=0), full diffuse.
//                     for metals (metalness=1), no diffuse (absorbed).
//   albedo — the base colour of the material (water colour in our case)
//   / π — normalizes the Lambertian lobe so the hemispherical integral
//         equals exactly 1.0 (energy conservation)
//
// For water specifically:  water is a dielectric (metalness = 0), so the
// full (1 − F) fraction is available for the diffuse term.  At normal
// incidence, F ≈ 0.023, so ~97.7% of light enters the water and can
// scatter diffusely.  At grazing angles, F → 1, so the diffuse term
// vanishes — this is why water looks like a mirror at the horizon.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 6 — HDR Environment Map Reflections (Prefiltered)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// For the specular environment contribution, we integrate the BRDF over
// the hemisphere of incoming directions:
//
//   Loₑₙᵥ = ∫ fₛ(L, V) · Lₑₙᵥ(L) · (N·L) dω
//
// This integral is intractable at runtime for arbitrary environment maps.
// The solution (by Epic Games / UE4) is PMREM:
//
//   PMREM (Pre-filtered Multi-Resolution Environment Map) pre-convolves
//   the source HDR environment into a mip chain where each mip level
//   represents the integral of a GGX lobe at a specific roughness:
//
//     MIP(level) = ∫ R · Dₐₗₚₕₐ(level)(R · H) · (N·R) dω
//
//   where α(level) increases with the mip level.  At mip 0 (roughness=0),
//   the map is the original HDR environment.  At higher mips, the map is
//   progressively blurred.
//
// At runtime, we select the mip level based on roughness:
//
//     lod = roughness · maxMipLevel
//     envColor = textureLod(uEnvMap, R, lod)
//
// where R = reflect(-V, N) = -V + 2·(N·V)·N is the perfect mirror
// reflection direction.
//
// Three.js PMREMGenerator performs this pre-filtering automatically from
// a CubeTexture or Scene, producing a CubeTexture with the correct mip
// chain for GGX roughness integration.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 7 — BRDF Integration (Precomputed or Analytical)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The full environment integral also depends on the Fresnel term F, which
// varies with the viewing angle.  To handle this, we separate the integral
// using the Schlick Fresnel form:
//
//   ∫ F(H,V) · Lₑₙᵥ(H) · (N·H) dω
//   = F₀ · ∫ (1-F₀) · L · (N·H) dω  +  ∫ F₀ · L · (N·H) dω
//   = (1-F₀) · ∫ L · (N·H) dω  +  F₀ · ∫ L · (N·H) dω
//
// The two integrals depend only on (N·V) and roughness α, so they can be
// precomputed into a 2D lookup texture (the BRDF LUT):
//
//   BRDF_LUT[NdotV][roughness] = (integral, scale)
//
// Then:
//   Loₑₙᵥ = envColor · (BRDF_scale · F₀ + BRDF_integral)
//
// When a BRDF LUT is not available, we use the closed-form approximation:
//
//   perceptualRoughness = (1 − N·V)⁵
//   scale = perceptualRoughness · (1 − F₀)
//   integral = F₀
//
// This is less accurate but requires no texture lookup.
//
// Reference:  Epic Games, "Moving Frostbite to PBR"
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 8 — Fresnel-Weighted Irradiance (Diffuse Environment)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// The diffuse component also needs environment lighting.  For a perfect
// Lambertian surface, the irradiance from an environment map is:
//
//   E = ∫ Lₑₙᵥ(L) · (N·L) dω
//
// This can be precomputed into spherical harmonics (SH) coefficients,
// which allow O(1) evaluation at any normal direction.  Three.js provides
// PMREMGenerator which can generate an irradiance CubeTexture.
//
// The Fresnel-weighted diffuse environment is:
//
//   Loₔ = (1 − F(N,V)) · irradiance(N)
//
// where F(N,V) uses the Schlick approximation with cosθ = N·V (not H·V).
// This ensures that at grazing angles, the diffuse contribution vanishes
// (all light is reflected specularly).
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 9 — Subsurface Scattering Approximation
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// Water is partially transparent.  Light that enters the surface can
// scatter beneath the surface and exit nearby, creating a characteristic
// translucent glow.  Full subsurface scattering is expensive, so we use
// a screen-space approximation:
//
//   SSS = sssColor · max(0.0, dot(V, T)) · (1.0 − F(N,V)) · wrapLight
//
// Where:
//   T — the tangent vector (perpendicular to the wave normal, along the
//       wave crest).  This biases the SSS effect along the surface.
//   wrapLight — a wrapped diffuse term:  max(0, (N·L + 0.33) / 1.33)
//   (1 − F) — SSS only matters when light enters the surface
//
// This creates a subtle rim-lighting effect that simulates light
// penetrating the water surface and scattering beneath it.
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// EQUATION 10 — ACES Filmic Tone Mapping
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// HDR colour values (which can exceed 1.0) must be mapped to the LDR
// range [0, 1] for display.  ACES (Academy Color Encoding System) is
// the industry-standard filmic tone mapping curve:
//
//   Cₐₜₛ = (C · (2.51 · C + 0.03)) / (C · (2.43 · C + 0.59) + 0.14)
//
// This S-shaped curve preserves highlights better than Reinhard
// (C / (C + 1)) while maintaining a natural contrast roll-off.  It was
// developed by the Academy of Motion Picture Arts and Sciences.
//
// Reference:  Burley & Borshukov (2014), "An Analytic Model for
// Phase One's Tone Reproduction Preview."
//
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

const fragmentShader = /* glsl */ `
  precision highp float;

  varying vec3 vWorldPosition;
  varying vec3 vNormal;
  varying float vElevation;
  varying float vBreaking;

  // ── PBR uniforms ──────────────────────────────────────────────────────
  uniform float uRoughness;
  uniform float uMetalness;
  uniform vec3  uF0;              // base reflectance (dielectric Fresnel)
  uniform vec3  uLightDir;        // directional light direction (world space)
  uniform vec3  uLightColor;      // directional light colour (HDR)
  uniform samplerCube uEnvMap;    // PMREM-processed environment map
  uniform samplerCube uIrradianceMap;  // irradiance for diffuse env
  uniform sampler2D uBRDFLUT;     // precomputed BRDF lookup (optional)
  uniform float uTime;

  // ── Water appearance uniforms ─────────────────────────────────────────
  uniform vec3  uDeepColor;
  uniform vec3  uShallowColor;
  uniform vec3  uFoamColor;
  uniform float uFoamThreshold;
  uniform vec3  uSSSColor;
  uniform float uSSSScale;

  // ── Procedural foam uniforms ──────────────────────────────────────────
  uniform float uFoamBreakingThreshold;  // divergence threshold for breaking
  uniform float uFoamNoiseScale;         // spatial frequency of foam noise
  uniform float uFoamNoiseDrift;         // drift speed of foam pattern
  uniform float uShoreDistance;          // distance to shoreline (Infinity to disable)
  uniform float uShoreFoamWidth;         // width of shoreline foam band

  // ── Constants ─────────────────────────────────────────────────────────
  const float PI = 3.141592653589793;

  // ───────────────────────────────────────────────────────────────────────
  // Procedural value noise for foam pattern
  // Hash-based noise with smooth interpolation — no textures required.
  // Produces a cellular / cellular-foam pattern when thresholded.
  // ───────────────────────────────────────────────────────────────────────
  // Hash function: maps a 2D coordinate to a pseudo-random float in [0, 1]
  float hash(vec2 p) {
    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123);
  }

  // Smooth value noise: bilinearly interpolates hash values at grid corners
  float noise(vec2 p) {
    vec2 i = floor(p);
    vec2 f = fract(p);
    // Smoothstep for C1 continuity
    vec2 u = f * f * (3.0 - 2.0 * f);

    float a = hash(i);
    float b = hash(i + vec2(1.0, 0.0));
    float c = hash(i + vec2(0.0, 1.0));
    float d = hash(i + vec2(1.0, 1.0));

    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
  }

  // Foam noise: combines two octaves of value noise for a cellular pattern.
  // The noise is advected by time * drift to simulate foam movement.
  float foamNoise(vec2 pos, float time, float scale, float drift) {
    // First octave — large-scale foam patches
    vec2 p1 = pos * scale / 100.0 + vec2(drift * 0.3, drift * 0.1) * time;
    float n1 = noise(p1);
    // Second octave — finer detail, higher frequency
    vec2 p2 = pos * scale / 50.0 + vec2(-drift * 0.1, drift * 0.4) * time;
    float n2 = noise(p2);
    // Combine: average the two octaves, then sharpen with smoothstep
    return smoothstep(0.2, 0.8, (n1 * 0.6 + n2 * 0.4));
  }

  // ───────────────────────────────────────────────────────────────────────
  // EQUATION 1: Schlick Fresnel Approximation
  // F(θ) = F₀ + (1 − F₀) · (1 − cos θ)⁵
  //
  // cosTheta is the dot product between the half-vector H and the view
  // direction V for specular, or N·V for diffuse Fresnel.
  // The power-5 term ensures F → 1 at grazing angles.
  // ───────────────────────────────────────────────────────────────────────
  vec3 fresnelSchlick(float cosTheta, vec3 F0) {
    return F0 + (1.0 - F0) * pow(1.0 - cosTheta, 5.0);
  }

  // ───────────────────────────────────────────────────────────────────────
  // EQUATION 2: GGX / Trowbridge-Reitz Normal Distribution Function
  // D = α² / ( π · ( (N·H)² · (α² − 1) + 1 )² )
  //
  // α = roughness² gives perceptually linear control.
  // The denominator's squared term creates the characteristic GGX tail.
  // ───────────────────────────────────────────────────────────────────────
  float distributionGGX(float NdotH, float roughness) {
    float a   = roughness * roughness;
    float a2  = a * a;
    float d   = NdotH * NdotH * (a2 - 1.0) + 1.0;
    return a2 / (PI * d * d);
  }

  // ───────────────────────────────────────────────────────────────────────
  // EQUATION 3: Smith Geometric Shadowing (Schlick-GGX approximation)
  // G₁(X) =  (X·N) / ( (X·N) · (1 − k) + k )
  // k = roughness² / (2 · (roughness + 1)²)
  // G  =  G₁(V) · G₁(L)
  //
  // This estimates the fraction of microfacets visible from both the
  // light and the camera simultaneously.
  // ───────────────────────────────────────────────────────────────────────
  float geometrySchlickGGX(float NdotX, float roughness) {
    float r = roughness + 1.0;
    float k = (roughness * roughness) / (r * r);
    return NdotX / (NdotX * (1.0 - k) + k);
  }

  float geometrySmith(float NdotV, float NdotL, float roughness) {
    return geometrySchlickGGX(NdotV, roughness) *
           geometrySchlickGGX(NdotL, roughness);
  }

  // ───────────────────────────────────────────────────────────────────────
  // EQUATION 7: BRDF Integration (analytical fallback)
  // When no BRDF LUT is available, use the closed-form approximation:
  //   perceptualRoughness = (1 − N·V)⁵
  //   scale = perceptualRoughness · (1 − F₀)
  //   integral = F₀
  // ───────────────────────────────────────────────────────────────────────
  vec3 brdfIntegrationAnalytical(float NdotV, vec3 F0) {
    // The (1-NdotV)^5 term approximates the precomputed BRDF scale.
    // At NdotV=1 (straight on), scale=0.  At NdotV=0 (grazing), scale=1.
    float perceptualRoughness = pow(1.0 - NdotV, 5.0);
    return perceptualRoughness * (1.0 - F0) + F0;
  }

  void main() {
    // ── Surface normal (analytical Gerstner) ────────────────────────────
    vec3 N = normalize(vNormal);

    // ── View direction ──────────────────────────────────────────────────
    vec3 V = normalize(cameraPosition - vWorldPosition);

    // ── Light direction (uniform, already normalised on JS side) ────────
    vec3 L = normalize(uLightDir);
    vec3 H = normalize(V + L);                       // half-vector

    float NdotV = max(dot(N, V), 0.001);  // avoid division by zero
    float NdotL = max(dot(N, L), 0.0);
    float NdotH = max(dot(N, H), 0.0);
    float HdotV = max(dot(H, V), 0.0);

    // ── EQUATION 1: Fresnel (Schlick) ───────────────────────────────────
    // F₀ is the reflectance at normal incidence.  For water with IOR 1.33:
    //   F₀ = ((1.33 − 1) / (1.33 + 1))² ≈ 0.023
    // We pass it as a uniform so the caller can tweak it.
    vec3 F = fresnelSchlick(HdotV, uF0);

    // ── EQUATION 2: Normal Distribution Function (GGX) ──────────────────
    float D = distributionGGX(NdotH, uRoughness);

    // ── EQUATION 3: Geometric Shadowing (Smith) ─────────────────────────
    float G = geometrySmith(NdotV, NdotL, uRoughness);

    // ── EQUATION 4: Cook-Torrance specular BRDF ─────────────────────────
    // kₛ = (D · G · F) / (4 · NdotV · NdotL)
    vec3 kSpec = (D * G * F) / (4.0 * NdotV * NdotL);

    // ── EQUATION 5: Diffuse albedo with energy conservation ─────────────
    // Deep water → crest gradient
    float t = smoothstep(-4.0, 4.0, vElevation);
    vec3 albedo = mix(uDeepColor, uShallowColor, t);

    // kₔ = (1 − F) · (1 − metalness) · albedo / π
    // For water (metalness = 0) the full (1 − F) fraction is diffuse.
    vec3 kDiff = (1.0 - F) * (1.0 - uMetalness) * albedo / PI;

    // ── Direct lighting ─────────────────────────────────────────────────
    // Lo = (kₛ + kₔ) · Li · (N·L)
    vec3 directLighting = (kSpec + kDiff) * uLightColor * NdotL;

    // ── EQUATION 6: Environment map reflection (prefiltered) ────────────
    // R = reflect(−V, N)  =  −V + 2·(N·V)·N
    vec3 R = reflect(-V, N);

    // PMREM stores prefiltered lobes in the mip chain.  The lod value
    // maps roughness ∈ [0, 1] to the mip range [0, maxMip].
    float envMapRoughness = uRoughness;
    vec3 envColor = textureLod(uEnvMap, R, envMapRoughness * 4.0).rgb;

    // ── EQUATION 7: BRDF Integration ────────────────────────────────────
    // Scale the environment reflection by the precomputed/analytical BRDF.
    // This ensures energy conservation for rough surfaces.
    vec3 brdfFactor;
    #ifdef USE_BRDF_LUT
      // Use the 2D BRDF lookup texture if available.
      // x-axis: NdotV  y-axis: roughness
      vec2 brdfUV = vec2(NdotV, uRoughness);
      brdfFactor = texture(uBRDFLUT, brdfUV).rg * F0 + F0;
    #else
      // Analytical approximation (no texture needed)
      brdfFactor = brdfIntegrationAnalytical(NdotV, uF0);
    #endif

    vec3 envSpecular = envColor * brdfFactor;

    // ── EQUATION 8: Fresnel-weighted irradiance (diffuse env) ───────────
    // The diffuse environment contribution uses the irradiance map,
    // weighted by (1 − F) to ensure energy conservation.
    vec3 irradiance = texture(uIrradianceMap, N).rgb;
    vec3 F_diffuse = fresnelSchlick(NdotV, uF0);
    vec3 envDiffuse = (1.0 - F_diffuse) * irradiance * albedo;

    // ── EQUATION 9: Subsurface scattering approximation ─────────────────
    // SSS = sssColor · max(0, dot(V, tangent)) · (1-F) · wrapLight
    // Creates a rim-lighting effect along wave crests.
    vec3 T = normalize(V - N * dot(V, N));  // tangent perpendicular to V and N
    float wrapLight = max(0.0, dot(N, L) * 0.5 + 0.5);  // wrapped diffuse
    float sss = max(0.0, dot(V, T)) * (1.0 - F_diffuse.r) * wrapLight;
    vec3 sssContribution = uSSSColor * sss * 0.5;

    // ── Procedural foam / whitecaps ─────────────────────────────────────
    // Multi-factor foam: foamAmount = crestFactor * breakingFactor * noiseMask
    //
    // Factor 1 — Crest elevation: foam only appears near wave crests.
    // Factor 2 — Wave breaking: foam is stronger where waves compress
    //   (positive horizontal velocity divergence from the vertex shader).
    // Factor 3 — Procedural noise: masks the foam with a cellular pattern
    //   so it looks like organic foam patches rather than a smooth gradient.
    // Factor 4 — Shoreline: additional foam near the shore boundary.

    // Crest factor: smooth transition from no foam to full foam at crests
    float crestFactor = smoothstep(uFoamThreshold - 1.0, uFoamThreshold + 1.0, vElevation);

    // Breaking factor: how much the wave is compressing (from vertex shader)
    float breakingFactor = clamp(vBreaking / uFoamBreakingThreshold, 0.0, 1.0);

    // Noise mask: procedural cellular pattern, advected over time
    float n = foamNoise(vWorldPosition.xz, uTime, uFoamNoiseScale, uFoamNoiseDrift);

    // Shoreline foam: smooth band near the shore boundary
    float shoreFactor = 0.0;
    if (uShoreDistance < 10000.0) {
      float distToShore = abs(length(vWorldPosition.xz) - uShoreDistance);
      shoreFactor = 1.0 - smoothstep(0.0, uShoreFoamWidth, distToShore);
    }

    // Combine: foam needs crest AND (breaking OR shore), masked by noise
    float foamAmount = crestFactor * max(breakingFactor, shoreFactor) * n;

    // Foam contribution: blend foam color over the water color
    vec3 foamContribution = uFoamColor * foamAmount * 0.8;

    // ── Combine all contributions ───────────────────────────────────────
    vec3 color = directLighting + envSpecular + envDiffuse + sssContribution + foamContribution;

    // ── EQUATION 10: ACES Filmic Tone Mapping ──────────────────────────
    // Cₐₜₛ = (C · (2.51 · C + 0.03)) / (C · (2.43 · C + 0.59) + 0.14)
    // Maps HDR values to [0, 1] with a cinematic S-curve.
    color = (color * (2.51 * color + 0.03)) / (color * (2.43 * color + 0.59) + 0.14);

    // Gamma correction (sRGB output)
    color = pow(max(color, vec3(0.0)), vec3(1.0 / 2.2));

    gl_FragColor = vec4(color, 1.0);
  }
`;

// ---------------------------------------------------------------------------
// Helper: normalize a 2D direction and pack wave config into arrays
// ---------------------------------------------------------------------------

function normalizeDirection2(d: [number, number]): [number, number] {
  const len = Math.sqrt(d[0] * d[0] + d[1] * d[1]);
  if (len === 0) return [1, 0];
  return [d[0] / len, d[1] / len];
}

// ---------------------------------------------------------------------------
// WaterMesh class
// ---------------------------------------------------------------------------

export class WaterMesh extends Mesh<BufferGeometry, ShaderMaterial> {
  private _timeUniform: { value: number };

  constructor(config: Partial<WaterMeshConfig> = {}) {
    const resolved: WaterMeshConfig = { ...defaultConfig, ...config };
    const waves = resolved.waves;

    // -- Geometry ----------------------------------------------------------
    const geometry = new PlaneGeometry(
      resolved.size,
      resolved.size,
      resolved.segments,
      resolved.segments
    );
    geometry.rotateX(-Math.PI / 2);

    // -- Prepare uniform arrays --------------------------------------------
    const waveCount = Math.min(waves.length, MAX_WAVES);

    const amplitudeArr: number[] = [];
    const wavelengthArr: number[] = [];
    const speedArr: number[] = [];
    const directionArr: number[] = []; // interleaved dx, dz
    const steepnessArr: number[] = [];

    for (let i = 0; i < waveCount; i++) {
      const w = waves[i];
      const [dx, dz] = normalizeDirection2(w.direction);

      amplitudeArr.push(w.amplitude);
      wavelengthArr.push(w.wavelength);
      speedArr.push(w.speed);
      directionArr.push(dx, dz);
      steepnessArr.push(w.steepness);
    }

    // Pad to MAX_WAVES with zeros
    while (amplitudeArr.length < MAX_WAVES) {
      amplitudeArr.push(0);
      wavelengthArr.push(1);
      speedArr.push(0);
      directionArr.push(1, 0);
      steepnessArr.push(0);
    }

    // -- PBR parameters ----------------------------------------------------
    //
    // F₀ (Schlick Fresnel at normal incidence) for water.
    // Derived from the index of refraction:  F₀ = ((ior − 1) / (ior + 1))²
    // With ior = 1.33 for water:  F₀ ≈ 0.023
    const ior = resolved.ior ?? 1.33;
    const f0Scalar = ((ior - 1) / (ior + 1)) ** 2;
    const f0 = [f0Scalar, f0Scalar, f0Scalar];

    const roughness = resolved.roughness ?? 0.15;
    const metalness = resolved.metalness ?? 0.0;

    // -- Material ----------------------------------------------------------
    const material = new ShaderMaterial({
      vertexShader,
      fragmentShader,
      uniforms: {
        uTime: { value: 0 },
        uWaveCount: { value: waveCount },
        uAmplitude: { value: amplitudeArr },
        uWavelength: { value: wavelengthArr },
        uSpeed: { value: speedArr },
        uDirection: { value: directionArr },
        uSteepness: { value: steepnessArr },

        // PBR uniforms
        uRoughness: { value: roughness },
        uMetalness: { value: metalness },
        uF0: { value: new Vector3(...f0) },
        uLightDir: { value: new Vector3(0.5, 1.0, 0.3).normalize() },
        uLightColor: { value: new Vector3(1.5, 1.3, 1.0) },
        uEnvMap: { value: resolved.envMap || null },
        uIrradianceMap: { value: resolved.irradianceMap || null },
        uBRDFLUT: { value: resolved.brdfLUT || null },

        // Water appearance uniforms
        uDeepColor: {
          value: new Vector3(
            ...(resolved.deepColor ?? [0.0, 0.05, 0.15])
          ),
        },
        uShallowColor: {
          value: new Vector3(
            ...(resolved.shallowColor ?? [0.0, 0.5, 0.6])
          ),
        },
        uFoamColor: {
          value: new Vector3(...(resolved.foamColor ?? [0.95, 0.95, 0.95])),
        },
        uFoamThreshold: { value: resolved.foamThreshold ?? 2.5 },
        uSSSColor: {
          value: new Vector3(...(resolved.sssColor ?? [0.0, 0.35, 0.45])),
        },
        uSSSScale: { value: resolved.sssScale ?? 8.0 },
      },
      side: DoubleSide,
      lights: false, // We handle lighting manually in the shader
    });

    super(geometry, material);

    this._timeUniform = material.uniforms.uTime;

    // Y = 0 is the water surface.
    this.position.y = 0;
  }

  /**
   * Call every frame to advance the wave animation.
   */
  update(time: number): void {
    this._timeUniform.value = time;
  }
}